name: Go Build Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-build-release:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - uses: conventional-actions/setup-netrc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: version
        name: Determine next version
        uses: conventional-actions/next-version@v1
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Go Version
        uses: conventional-actions/go-version@v1
        with:
          version: ${{steps.version.outputs.version}}
      - name: Go Build
        uses: conventional-actions/go-build@v1
        with:
          platforms: |
            linux/amd64
            linux/arm64
            darwin/amd64
            darwin/arm64
            windows/amd64
      - name: Create release
        uses: conventional-actions/create-release@v1
        with:
          tag_name: ${{steps.version.outputs.version}}
          artifacts: 'bin1_linux_amd64'

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
