name: Go Kart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kart:
    name: Kart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - id: gokart
        uses: conventional-actions/go-kart@v1
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{steps.gokart.outputs.output_path}}
