name: Go Revive

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  revive:
    name: Revive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - id: gorevive
        uses: conventional-actions/go-revive@v0.0.5
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{steps.gorevive.outputs.output_path}}
