name: Go Sec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gosec:
    name: Go Sec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - id: gosec
        uses: conventional-actions/go-sec@v0.0.1
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{steps.gosec.outputs.output_path}}
