name: Go Vet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vet:
    name: Go Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - uses: conventional-actions/go-vet@v1.0.2
