name: Sample 1

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            winchci/test-project
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --allow-insecure-entitlement network.host
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          file: docker/sample1/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          allow: network.host
          cache-from: type=gha
          cache-to: type=gha
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#          build-args: |
#            foo
#          target: container

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
