name: Sample 1

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello from sample 1"

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
