name: Setup Docker Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-docker-scan:
    name: Setup Docker Scan
    runs-on: ubuntu-latest
    steps:
      - uses: conventional-actions/setup-netrc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - uses: conventional-actions/setup-docker-scan@v1.1.2
        with:
          token: ${{secrets.SNYK_AUTH_TOKEN}}

env:
  SNYK_AUTH_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
